name: Codex QA Pipeline

on:
  pull_request:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependências
        run: CYPRESS_INSTALL_BINARY=0 npm ci

      - name: Verificar qualidade (eslint + prettier)
        run: npm run lint && npm run format:check

      - name: Testar TypeScript
        run: npm run type-check

      - name: Testar segurança (npm audit)
        run: npm audit --audit-level=high || true
        continue-on-error: true

      - name: Executar testes unitários
        run: npm run test

      - name: Build da aplicação
        run: npm run build
